- name: Installing apache
  hosts: 3.87.138.112
  become: yes
  become_user: root

  tasks:
  - name: "Installing httpd"
    apt:
      name: apache2
      state: present

  - name: Start and enable apache2 service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Pull Docker image
    docker_image:
      name: 54.89.239.176:8083/petshop:latest
      source: pull

  - name: Run Docker container
    docker_container:
      name: pet1
      image: 54.89.239.176:8083/petshop:latest
      state: started
      ports:
      - "8082:8080"
