- name: Installing apache
  hosts: 3.87.138.112
  become: yes
  become_user: root

  tasks:
  - name: "Installing httpd"
    package:
      name: apache2
        state: present

  - name: Start and enable apache2 service
    service:
      name: apache2
      state: started
      enabled: yes
